language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rakesh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rakesh/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-936360013704"
  bucket_path: "docker"
  on:
    branch: master
  acess_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
